spring.application.name=demo
spring.ai.openai.api-key=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
openai.api.key=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

spring.datasource.url=jdbc:mysql://localhost:3306/aidnd?useSSL=false&serverTimezone=UTC
spring.datasource.username=Yanetsuru
spring.datasource.password=Dragonbalz
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
